added feature to auto download common_features

diff --git a/common_functions b/common_functions
--- a/common_functions
+++ b/common_functions
@@ -2,16 +2,22 @@
 #
 # Description: common_functions
 # Author: Steve Stonebraker
-# use:
+# useage:
 # readonly ourPath="$(dirname $0)"
 # readonly commonFunctions="$ourPath/common_functions"
-# if [ -e "$commonFunctions" ]; then
-#   source "$commonFunctions"
-# else
-#   echo "common_functions not found"
+# if [ ! -e "$commonFunctions" ]; then
+#       echo "common_functions not found... downloading"
+#         cd $ourPath
+#         curl -s -O  "https://raw.github.com/ssstonebraker/braker-scripts/master/common_functions"
 # fi
-#
-#
+# 
+# if [ -e "$commonFunctions" ]; then
+#         source "$commonFunctions"
+#         print_good "loaded commonFunctions file"
+# else
+#         echo "common_functions not found... exiting"
+#         exit 1;
+# fi
 
 ########################################
 function print_status ()
