added linode scripts and some hardcoded stuff

diff --git a/common_functions b/common_functions
--- a/common_functions
+++ b/common_functions
@@ -134,3 +134,145 @@ restart_service_mem_ge_x () {
 
 }
 ########################################
+########################################
+kill_process_with_name () {
+    #kill_process_with_name (some_process_name)
+        current_script=`basename $0`
+        process_name=$1
+        pids=$( ps aux | grep "${process_name}" | grep -v 'grep' | grep -v "$current_script" | awk '{print $2}' )
+        for pid in $pids
+                do
+                echo "$process_name is running with pid $pid ..."
+                if ! kill $pid > /dev/null 2>&1; then
+                        echo "Could not send SIGTERM to $process_nameprocess with $pid .. trying kill -9" >&2
+                        if ! kill -9 $pid > /dev/null 2>&1; then
+                                echo "Unable to kill $pid with kill -9"
+                        else
+                                echo "Successfully killed $process_name with PID $pid!"
+                        fi
+                 else
+                        echo "Successfully killed $process_name with PID $pid!"
+        fi
+done
+        echo "$pids"
+}
+
+
+########################################
+
+function system_update_hostname {
+    # system_update_hostname(system hostname)
+    if [ -z "$1" ]; then
+        echo "system_update_hostname() requires the system hostname as its first argument"
+        return 1;
+    fi
+    echo $1 > /etc/hostname
+    hostname -F /etc/hostname
+    sed -i -e "s/^127\.0\.1\.1\s.*$/$$1/" /etc/hosts
+    /etc/init.d/hostname restart
+}
+function system_primary_ip {
+  # returns the primary IP assigned to eth0
+  echo $(ifconfig eth0 | awk -F: '/inet addr:/ {print $2}' | awk '{ print $1 }')
+}
+
+function lower {
+    # helper function
+    echo $1 | tr '[:upper:]' '[:lower:]'
+}
+
+
+function system_add_user {
+    # system_add_user(username, password, groups, shell=/bin/bash)
+    USERNAME=`lower $1`
+    PASSWORD=$2
+    SUDO_GROUP=$3
+    SHELL=$4
+    if [ -z "$4" ]; then
+        SHELL="/bin/bash"
+    fi
+    useradd --create-home --shell "$SHELL" --user-group --groups "$SUDO_GROUP" "$USERNAME"
+    echo "$USERNAME:$PASSWORD" | chpasswd
+}
+
+function system_add_system_user {
+    # system_add_system_user(username, home, shell=/bin/bash)
+    USERNAME=`lower $1`
+    HOME_DIR=$2
+    SHELL=$3
+    if [ -z "$3" ]; then
+        SHELL="/bin/bash"
+    fi
+    useradd --system --create-home --home-dir "$HOME_DIR" --shell "$SHELL" --user-group $USERNAME
+}
+
+function system_lock_user {
+    # system_lock_user(username)
+    passwd -l "$1"
+}
+
+function system_get_user_home {
+    # system_get_user_home(username)
+    cat /etc/passwd | grep "^$1:" | cut --delimiter=":" -f6
+}
+
+function system_user_add_ssh_key {
+    # system_user_add_ssh_key(username, ssh_key)
+    USERNAME=`lower $1`
+    USER_HOME=`system_get_user_home "$USERNAME"`
+    sudo -u "$USERNAME" mkdir "$USER_HOME/.ssh"
+    sudo -u "$USERNAME" touch "$USER_HOME/.ssh/authorized_keys"
+    sudo -u "$USERNAME" echo "$2" >> "$USER_HOME/.ssh/authorized_keys"
+    chmod 0600 "$USER_HOME/.ssh/authorized_keys"
+}
+
+function system_sshd_edit_bool {
+    # system_sshd_edit_bool (param_name, "Yes"|"No")
+    VALUE=`lower $2`
+    if [ "$VALUE" == "yes" ] || [ "$VALUE" == "no" ]; then
+        sed -i "s/^#*\($1\).*/\1 $VALUE/" /etc/ssh/sshd_config
+    fi
+}
+
+function system_sshd_permitrootlogin {
+    system_sshd_edit_bool "PermitRootLogin" "$1"
+}
+
+function system_sshd_passwordauthentication {
+    system_sshd_edit_bool "PasswordAuthentication" "$1"
+}
+
+
+function system_get_codename {
+    echo `lsb_release -sc`
+}
+
+function system_get_release {
+    echo `lsb_release -sr`
+}
+
+function system_sshd_pubkeyauthentication {
+    system_sshd_edit_bool "PubkeyAuthentication" "$1"
+}
+
+function system_update_locale_en_US_UTF_8 {
+    # locale-gen en_US.UTF-8
+    dpkg-reconfigure locales
+    update-locale LANG=en_US.UTF-8
+}
+
+function restart_services {
+    # restarts upstart services that have a file in /tmp/needs-restart/
+    for service_name in $(ls /tmp/ | grep restart-* | cut -d- -f2-10); do
+        service $service_name restart
+        rm -f /tmp/restart-$service_name
+    done
+}
+
+function restart_initd_services {
+    # restarts upstart services that have a file in /tmp/needs-restart/
+    for service_name in $(ls /tmp/ | grep restart_initd-* | cut -d- -f2-10); do
+        /etc/init.d/$service_name restart
+        rm -f /tmp/restart_initd-$service_name
+    done
+}
